version: "3.8"
services:
  node:
    container_name: project-api-node
    image: "node:latest"
    working_dir: /home/node/app
    command:
      - /bin/bash
      - "-c"
      - "npm install && npm run start"
    ports:
      - "3000:3000"
    volumes:
      - "./src:/home/node/app"
  mongos:
    container_name: project-api-mongos
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
